# Numpy 100 Exercise

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

# 1. **Import** **NumPy**

In [3]:
import numpy as np
print(np.__version__)

1.26.4


# **2. Create a NumPy Array**

In [6]:
#create a new array from 0 to 9
arr = np.arange(10,)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


# **3. Create an Array of Zeros**

In [9]:
arr = np.zeros((3, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# **4. Create an Array of Ones**

In [10]:
arr = np.ones((2, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# **5. Create an Identity Matrix**

In [11]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# **6. Create a Random Array**

In [12]:
arr = np.random.rand(2, 3)
print(arr)

[[0.48827335 0.6774251  0.57557715]
 [0.00407587 0.55210972 0.20145951]]


# **7. Reshape an Array**

In [13]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# **8. Find the Maximum Value**

In [14]:
arr = np.array([10, 20, 5, 30])
print(np.max(arr))

30


# **9. Find the Minimum Value**

In [15]:
arr = np.array([10, 20, 5, 30])
print(np.min(arr))

5


# **10. Find the Mean**


In [16]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))

3.0
